### ISSUE TITLE
Multiple-Grids demo

### ISSUE THREAD

**Issue by willsolve** [openfin/fin-hypergrid#530] opened 2017-02-11 01:25 UTC
I'm getting the following error with the multiple-grids.html demo:
`Canvas.js:284 TypeError: Cannot read property 'length' of undefined
    at Constructor.paintCellsByColumnsAndRows [as paintCells] (file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:24702:19)
    at Constructor.renderGrid (file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:25752:14)
    at Constructor.paint (file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:25473:18)
    at Canvas.paintNow (file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:20009:28)
    at Canvas.tickPaint (file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:19895:18)
    at Canvas.beginPainting.tickPainter (file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:19913:18)
    at file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:20371:27
    at Array.forEach (native)
    at paintLoopFunction (file:///C:/Users/user/Desktop/demo/fin-hypergrid/build/fin-hypergrid.js:20369:20)`

The problem happens when this is called on the second iteration/instance
`grid[i] = new fin.Hypergrid(options);`

I traced it to the following code, and if the reset line is commented out, then it renders again:
fin-hypergrid.js line 24691 (by-columns-and-rows.js line 52)

   if (paintCellsByColumnsAndRows.reset) {
        this.resetAllGridRenderers();
/*        paintCellsByColumnsAndRows.reset = false; */
        bundleRows.call(this, false);
        bundleColumns.call(this, true);
    } else if (paintCellsByColumnsAndRows.rebundle) {
        paintCellsByColumnsAndRows.rebundle = false;
        bundleColumns.call(this);
    }

**Comment by Dwaynekj** [comment] 2017-02-14 18:23
@willsolve Thanks for pointing this out. We will add to our backlog

**Comment by Dwaynekj** [comment] 2017-02-28 22:51
@joneit I think we should add a defaults rendererReset Property rather than [this](https://github.com/openfin/fin-hypergrid/blob/master/src/renderer/by-columns-and-rows.js#L52) pattern for `by-cells`, `by-columns`, `by-rows`

**Comment by vodanh109** [comment] 2017-03-09 03:53
Hi, I merged this fixed code into my Hypergrid.js file. It passed the error. However, when I try to reset the data, it still print out this error:
`Cannot read property 'top' of undefined
    at Constructor.getGridCellFromMousePoint`

**Comment by Dwaynekj** [comment] 2017-03-09 04:55
@vodanh109 Are you using alpha?

**Comment by vodanh109** [comment] 2017-03-09 08:04
@Dwaynekj,
I'm just using the latest release version, but merge the code u fixed for this issue

**Comment by Dwaynekj** [comment] 2017-03-09 15:57
So your saying this is your changeset from master? https://github.com/openfin/fin-hypergrid/pull/564/files

Could give alpha a try?

**Comment by vodanh109** [comment] 2017-03-10 03:09
Hi, I tried to build from Alpha by Gulp. But it has some errors. After remove some tasks (test, add-ons), and using the output file in my app, it caused another error. So can u give to me the final output file of Alpha

**Comment by Dwaynekj** [comment] 2017-03-10 04:50
This worked for me and out our Travis build. Could you confirm you ran an `npm install` prior to gulp?

**Comment by vodanh109** [comment] 2017-03-10 04:51
yes, of course. I ran npm install & up to date

**Comment by Dwaynekj** [comment] 2017-03-10 05:04
Ah, ok cool. Could you paste the error?

**Comment by vodanh109** [comment] 2017-03-10 08:07
If u mean the error when building alpha, here it is:
`
[15:06:28] Starting 'lint'...
[15:06:49] Finished 'lint' after 21 s
[15:06:49] Starting 'images'...
[15:06:51] Finished 'images' after 1.88 s
[15:06:51] Starting 'css-templates'...
[15:06:51] Finished 'css-templates' after 183 ms
[15:06:51] Starting 'dialogs-css-templates'...
[15:06:51] Finished 'dialogs-css-templates' after 33 ms
[15:06:51] Starting 'dialogs-html-templates'...
[15:06:51] Finished 'dialogs-html-templates' after 125 ms
[15:06:51] Starting 'test'...


  Base
    Module expected shape
      √ Should have the instance shape (100ms)
    extend
      √ Should create a new constructor
      Should extend with
        √ Should extend with HypergridError
        √ Should extend with deprecated
        √ Should extend with unwrap
    HypergridError
      √ should assign the message

  CSS
    Module expected shape
      1) Should have theinstance shape
      2) Should not be empty

  SelectionModel
    Module expected shape
      √ Should have the instance shape (80ms)


  7 passing (300ms)
  2 failing

  1) CSS Module expected shape Should have theinstance shape:
     H:\fin-hypergrid\css\index.js:4
'.hypergrid-container {
^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
      at Object.exports.runInThisContext (vm.js:76:16)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (H:\fin-hypergrid\test\css-test.js:16:23)
      at callFn (H:\fin-hypergrid\node_modules\mocha\lib\runnable.js:326:21)

  2) CSS Module expected shape Should not be empty:
     H:\fin-hypergrid\css\index.js:4
'.hypergrid-container {
^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
      at Object.exports.runInThisContext (vm.js:76:16)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (H:\fin-hypergrid\test\css-test.js:24:23)
      at callFn (H:\fin-hypergrid\node_modules\mocha\lib\runnable.js:326:21)



[15:06:57] 'test' errored after 6.14 s
[15:06:57] Error in plugin 'gulp-mocha'
Message:
    2 tests failed.
[15:06:57] 'build' errored after 29 s
[15:06:57] Error in plugin 'run-sequence(test)'
Error
    at finish (H:\fin-hypergrid\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (H:\fin-hypergrid\node_modules\run-sequence\index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (H:\fin-hypergrid\node_modules\orchestrat
or\index.js:264:8)
    at H:\fin-hypergrid\node_modules\orchestrator\index.js:275:23
    at finish (H:\fin-hypergrid\node_modules\orchestrator\lib\runTask.js:21:8)
    at Stream.<anonymous> (H:\fin-hypergrid\node_modules\orchestrator\lib\runTas
k.js:52:4)
    at Stream.f (H:\fin-hypergrid\node_modules\once\once.js:17:25)
    at emitOne (events.js:101:20)`

**Comment by Dwaynekj** [comment] 2017-03-10 14:51
@vodanh109 Whats your environment and node version?

**Comment by vodanh109** [comment] 2017-03-11 01:31
I'm working on Window 7 64 bit, node version v6.9.1

**Comment by Dwaynekj** [comment] 2017-03-14 14:15
One more test. Could you try develop?

**Comment by vodanh109** [comment] 2017-03-15 01:30
I didn't change anything yet. Just checkout Alpha then run Gulp. Do u mean that u want me to try develop sth? I'm just a newbie of hypergrid.

**Comment by vodanh109** [comment] 2017-03-17 09:40
Hi @Dwaynekj ,
After update few codes in gulp file, I can build successfully. It seem that the error was gone. Thanks a lot

**Comment by Dwaynekj** [comment] 2017-03-17 14:32
@vodanh109 So you can build but you still get that error? It seems you are using webpack, we don't have webpack in our builds

**Comment by vodanh109** [comment] 2017-03-18 10:22
Hi @Dwaynekj , I don't think Webpack is the root cause. Because actually the hypergrid is still working, but only console log throws some above errors

**Comment by Dwaynekj** [comment] 2017-03-18 22:01
interesting maybe we ought to do a quick screen sharing next week

**Comment by vodanh109** [comment] 2017-03-19 15:02
Okay. I can prepare for it. Pls comment whenever u want to do it

**Comment by Dwaynekj** [comment] 2017-03-20 15:24
The first half of week is pretty busy so how about this thursday/Friday around 3pm Est?

**Comment by Dwaynekj** [comment] 2017-03-29 17:16
@vodanh109 Lets use https://github.com/openfin/fin-hypergrid/issues/579 for future discussions

**Closed by Dwaynekj** 2017-03-29 17:16 UTC
Labels: bug

**Comment by Dwaynekj** [comment] 2017-04-05 19:51
Someone provided a workaround here https://github.com/openfin/fin-hypergrid/issues/579#issuecomment-291951540

**Comment by vodanh109** [comment] 2017-04-05 22:47
Hi @Dwaynekj,
Sorry for no response in recent days. I can handle the problem with window build. But what i care is the error with multi grid. Maybe you forgot this problem

**Comment by Dwaynekj** [comment] 2017-04-06 04:48
@vodanh109 The multi grid has already been resolved on develop and is on the latest alpha
