### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by eduardotang** [openfin/fin-hypergrid#28] opened 2015-04-24 06:49 UTC
All data disappears after you go back to the non sort state,
 asc ->  desc -> no sort (data gone)

while if you sort by another column before you go back to no sort on the same column, it is ok.

**Comment by stevewirts** [comment] 2015-04-25 15:06
I can't reproduce this,
is this the JSON behavior?

**Comment by eduardotang** [comment] 2015-04-26 02:32
yes the JSON behavior
and in the console i noticed 
Uncaught TypeError: Cannot set property '__i' of undefined

**Comment by stevewirts** [comment] 2015-05-04 20:06
that means one of the json objects you've provided was replaced with undefined somehow.
in order to get back to unsorted state I put __i index on the objects in order to have the native sort be stable

**Comment by stevewirts** [comment] 2015-05-04 20:08
I'm going to close this for now as I can't seem to reproduce it.  Let me know if it still is happening for you and we can dig in a little deeper.

**Closed by stevewirts** 2015-05-04 20:08 UTC

**Comment by eduardotang** [comment] 2015-05-05 03:35
i ran it through debugger, found that inside the toggleSort function
this copying makes use of __si  , but this is undefined

```javascript
         if (sortStateIndex === 0) {
                var newData = new Array(this.data.length);
                for (i = 0; i < this.data.length; i++) {
                    var each = this.data[i];
                    newData[each.__si] = each;
         }
                this.data = newData;
            }
```

**Comment by stevewirts** [comment] 2015-05-05 13:17
are you inserting new objects into the collection after things are running?
if so things need to be initialized.

**Comment by eduardotang** [comment] 2015-05-05 16:44
so everytime after i insert new objects , i have to call initDataIndexes?

**Comment by stevewirts** [comment] 2015-05-05 20:29
yes, unless you don't care about stable sorting and being able to go back
to the initial unsorted state

**Comment by stevewirts** [comment] 2015-05-05 20:32
I've just done a small refactoring, so if you change the underlying data
call "dataChanged()" on the behavior object...

        setData: function(jsonData) {
            this.data = jsonData;
            this.dataChanged();
        },

        dataChanged: function() {
            this.initDataIndexes();
            this.initColumnIndexes();
            this.changed();
        },

let me know how things work out....

**Comment by eduardotang** [comment] 2015-05-06 08:37
now the data wont be gone, and it stays at the descending state.
it's good enough.
thx

**Comment by stevewirts** [comment] 2015-05-06 13:31
I'll create an issue and implement a more robust solution,
Hypergrid should do something reasonable after inserting new data.

**Comment by eduardotang** [comment] 2015-05-17 10:55
your last commit move the call to initDataIndexes to setData, cause problem adding data to original array again

**Comment by stevewirts** [comment] 2015-05-17 16:10
reverted,
thanks :)
