### ISSUE TITLE
Columns to consume full width of fin-hypergrid canvas

### ISSUE THREAD

**Issue by 91c5ex** [openfin/fin-hypergrid#604] opened 2017-06-04 16:38 UTC
Hi,
Is there any way to achieve below functionality.
If  a grid has 5 columns can they consume full size of the canvas having equal distribution. and if no of columns increased by certain limit a horizontal scroll bar should get added.
Please take a look at fin-hypergrid [example](http://openfin.github.io/fin-hypergrid/)  in this a lot of white space is left between the last column Travel and the scroll bar. (I do not want to resize it manually)
I want fin-hypergrid to consume fill size of canvas in such scenario. and after certain limit scrollbar should get added.

**Comment by Dwaynekj** [comment] 2017-06-04 17:09
Duplicate of https://github.com/openfin/fin-hypergrid/issues/550
@91c5ex Let's discuss this on the link posted above

**Closed by Dwaynekj** 2017-06-04 17:09 UTC
